# Generated by Django 5.0.4 on 2024-04-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='admin',
            field=models.BooleanField(default=True),
        ),
    ]
