# Generated by Django 5.0.4 on 2024-05-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userdata_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='faculty',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='userdata',
            name='registered_as',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
