# Generated by Django 5.0.4 on 2024-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userdata_department_userdata_faculty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='department',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='registered_as',
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='registered_as',
            field=models.CharField(default='User', max_length=50),
        ),
    ]
